#!/bin/sh


ACTION=$1
JAIL_NAME=$2
JM_DIR=`cat ./.jm.config | grep JM_PATH | awk -F '=' '{print $2}'`
JM_LIB="./lib"

. $JM_LIB/core
. $JM_LIB/util

case $ACTION in
	create)
		core::create $JM_DIR $JAIL_NAME
		;;
	delete)
		core::delete $JM_DIR $JAIL_NAME
		;;
	list)
		core::list $JM_DIR | column -t
		;;
	start)
		core::start $JM_DIR $JAIL_NAME
		;;
	stop)
		core::stop $JM_DIR $JAIL_NAME
		;;
	restart)
                core::restart $JAIL_NAME
                ;;
	*)
		echo "invalid action"
		;;
esac
