#!/bin/sh

core::list() {
  for i in `ls $JM_DIR/` ; do
    jls name | grep -q "^$i$" && {
      echo "$i Running"
    } || {
      echo "$i"
    }
  done
}

core::start() {
  service jail onestart $JAIL_NAME
}

core::stop() {
  service jail onestop $JAIL_NAME
}

core::restart() {
  service jail onerestart $JAIL_NAME
}

core::create () {
  local IMAGE
  $IMAGE=$1
  util::check_name $JAIL_NAME || exit 1

  [ -e $JM_DIR/$JAIL_NAME ] && {
    echo "$JAIL_NAME exists"
    exit 1
  }

  [ -e $JM_DIR/.images/$IMAGE ] || {
    echo "$IMAGE does not exist"
    exit 1
  }

  echo "creating $JAIL_NAME"
  mkdir $JM_DIR/$JAIL_NAME
  tar xpf $JM_DIR/.images/$IMAGE -C $JM_DIR/$JAIL_NAME
  util::update_conf create $JAIL_NAME
}

core::delete() {
  util::check_name $JAIL_NAME || exit 1 # prevents removing silly things like "$JM_DIR/../../ " , which the following WILL evauluate as 'exists'

  [ -e $JM_DIR/$JAIL_NAME ] || {
    echo "$JAIL_NAME does not exist"
    exit 1
  }

  # if the jail is running, stop it
  jls name | grep -q "^$JAIL_NAME$" && core::stop

  echo "deleting $JAIL_NAME"
  chflags -R noschg $JM_DIR/$JAIL_NAME
  rm -rf $JM_DIR/$JAIL_NAME
  util::update_conf delete $JAIL_NAME
}

core::image_list() {
  ls $JM_DIR/.images
}

core::image_create() {
  local $JAIL="$1"
  tar -c -f $JM_DIR/.images/$JAIL.tar $JM_DIR/$JAIL
}

core::image_delete() {
  local $IMAGE="$1"
  rm -rf $JM_DIR/.images/$IMAGE.tar
}
