#!/bin/sh

core::list() {
  for i in `ls ${JM_DIR}/` ; do
    jls name | grep -q "^$i$" && {
      echo "$i Running"
    } || {
      echo "$i"
    }
  done
}

core::start() {
  local _NAME="$1"
  service jail onestart $_NAME
}

core::stop() {
  local _NAME="$1"
  service jail onestop $_NAME
}

core::restart() {
  local _NAME="$1"
  service jail onerestart $_NAME
}

core::create() {
  local IMAGE="$1"

  util::check_name $JAIL_NAME || util::handle_fatal "name $JAIL_NAME not valid"
  [ -e ${JM_DIR}/{$JAIL_NAME} ] && util::handle_fatal "$JAIL_NAME exists"
  [ -e ${JM_DIR}/.images/${IMAGE} ] || util::handle_fatal "$IMAGE does not exist"

  echo "creating $JAIL_NAME"
  mkdir ${JM_DIR}/${JAIL_NAME}
  tar xpf ${JM_DIR}/.images/${IMAGE} -C ${JM_DIR}/${JAIL_NAME}
  util::update_conf create $JAIL_NAME
}

core::delete() {
  util::check_name $JAIL_NAME || util::handle_fatal "name $JAIL_NAME not valid"
  [ -e ${JM_DIR}/${JAIL_NAME} ] || util::handle_fatal "$IMAGE does not exist"

  # if the jail is running, stop it
  jls name | grep -q "^${JAIL_NAME}$" && core::stop $JAIL_NAME

  echo "deleting $JAIL_NAME"
  chflags -R noschg ${JM_DIR}/${JAIL_NAME}
  rm -rf ${JM_DIR}/${JAIL_NAME}
  util::update_conf delete $JAIL_NAME
}

core::image_list() {
  ls -lh  ${JM_DIR}/.images | awk '{print $9" "$5}' | column -t
}

core::image_create() {
  local JAIL="$1"
  cd ${JM_DIR}/${JAIL}
  tar -c -f ${JM_DIR}/.images/${JAIL}.tar .
}

core::image_delete() {
  local IMAGE="$1"
  rm -rf ${JM_DIR}/.images/${IMAGE}.tar
}

core::startall() {
  for i in `ls ${JM_DIR}/` ; do
    core::start $i
  done
}

core::stopall() {
  for i in `ls ${JM_DIR}/` ; do
    core::stop $i
  done
}
