#!/bin/sh

util::bootstrap () {
## templating stuff

#cp $BASE_DIR/.templates/default/etc/rc.conf $BASE_DIR/$JAIL_NAME/etc/rc.conf
#cp $BASE_DIR/.templates/default/etc/resolv.conf $BASE_DIR/$JAIL_NAME/etc/resolv.conf
#mkdir $BASE_DIR/$JAIL_NAME/root/.ssh
#cp $BASE_DIR/.templates/default/root/.ssh/authorized_keys $BASE_DIR/$JAIL_NAME/root/.ssh/authorized_keys
#cp $BASE_DIR/.templates/default/etc/freebsd-update.conf $BASE_DIR/$JAIL_NAME/etc/freebsd-update.conf
#cp $BASE_DIR/.templates/default/etc/ssh/sshd_config $BASE_DIR/$JAIL_NAME/etc/ssh/sshd_config
}

util::handle_fatal() {
  echo "$1"
  exit 1
}

util::checkenv() {
  echo "check env stub"
}

# check for valid name
util::check_name() {
  local NAME="$1"
  echo $NAME | egrep -iqs "^[a-z0-9][.a-z0-9_-]{0,30}[a-z0-9]\$"
}

# update the main jail.conf
util::update_conf() {
  local ACTION=$1
  local JAIL_NAME=$2

  case $ACTION in
    create)
      grep -q "^${JAIL_NAME} {" /etc/jail.conf && { exit 1 ; } || {
        local ID=`jot -r 1 0 32767` # yes this is hacky but good enough
        echo "$JAIL_NAME { \$if = \"$ID\"; vnet.interface = \"epair\${if}b\"; } #jm_managed" >> /etc/jail.conf
      }
    ;;
    delete)
      grep -q "^${JAIL_NAME} {" /etc/jail.conf || { exit 1 ; } && {
        sed -i -e "/^${JAIL_NAME} {/ d" /etc/jail.conf
      }
    ;;
  esac
}
